#!/usr/bin/env python3
"""
Regenerates config_html_gz.h from captive-portal.html.

Run this after editing captive-portal.html, then rebuild the sketch.
The portal is served gzip-compressed to save flash (~9KB), so the two
"channel pre-selected" variants are baked in at gzip time rather than
built with String::replace() at request time.
"""
import gzip
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "captive-portal.html"
OUT = ROOT / "config_html_gz.h"

STABLE_OPTION = '<option value="stable">stable</option>'
STABLE_SELECTED = '<option value="stable" selected>stable</option>'
BETA_OPTION = '<option value="beta">beta</option>'
BETA_SELECTED = '<option value="beta" selected>beta</option>'


def gzip_bytes(data: bytes) -> bytes:
    # mtime=0 and compresslevel=9 for a deterministic, maximally-compressed output.
    return gzip.compress(data, compresslevel=9, mtime=0)


def to_c_array(name: str, data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    body = "\n".join(lines)
    return (
        f"const uint8_t {name}[] PROGMEM = {{\n{body}\n}};\n"
        f"const size_t {name}_LEN = {len(data)};\n"
    )


def main():
    html = SRC.read_text()
    assert html.count(STABLE_OPTION) == 1, "expected exactly one stable <option>"
    assert html.count(BETA_OPTION) == 1, "expected exactly one beta <option>"

    stable_html = html.replace(STABLE_OPTION, STABLE_SELECTED)
    beta_html = html.replace(BETA_OPTION, BETA_SELECTED)

    stable_gz = gzip_bytes(stable_html.encode())
    beta_gz = gzip_bytes(beta_html.encode())

    header = (
        "// Generated by tools/gen_config_html.py from captive-portal.html.\n"
        "// Do not edit by hand — edit captive-portal.html and regenerate:\n"
        "//   python3 tools/gen_config_html.py\n"
        "#pragma once\n\n"
        + to_c_array("CONFIG_HTML_STABLE_GZ", stable_gz)
        + "\n"
        + to_c_array("CONFIG_HTML_BETA_GZ", beta_gz)
    )
    OUT.write_text(header)
    print(
        f"wrote {OUT.name}: stable {len(stable_gz)}B, beta {len(beta_gz)}B "
        f"(source {len(html)}B)"
    )


if __name__ == "__main__":
    main()
